name: assignment01
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^1.1.7
  splashscreen:
    git:
      url: https://github.com/ramism16/SplashScreenFlutterPackage
      ref: master
  email_validator: ^2.0.1
  firebase_auth: ^1.3.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.2.1
  flutter_spinkit: ^5.0.0
  cloud_firestore: ^2.2.1
  intl: any



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/flutter-logo.png
    - assets/Ramis1.jpg

  fonts:
   - family: CenturyGothic
     fonts:
       - asset: assets/fonts/CenturyGothic.ttf
       - asset: assets/fonts/CenturyGothicItalic.ttf
         style: italic
       - asset: assets/fonts/CenturyGothicBold.ttf
         weight: 900