name: madlab7
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  splashscreen:
    git:
      url: https://github.com/ramism16/SplashScreenFlutterPackage.git
      ref: master

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - files/flutter-logo.png
    - files/recipeImages/

  fonts:
    - family: SFPro
      fonts:
        - asset: files/SF-Pro-Display-Regular.ttf
        - asset: files/SF-Pro-Display-Bold.ttf
          weight: 800